### ISSUE TITLE
test_unicode_input

### ISSUE THREAD

**Issue by siraben** [NicklasTegner/pypandoc#205]
Nixpkgs contributor here. `pypandoc` builds and passes all tests up to `test_unicode_input`, what could be causing this?

```
======================================================================
FAIL: test_unicode_input (tests.TestPypandoc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-python3.8-pypandoc-1.5.drv-0/source/tests.py", line 300, in test_unicode_input
    self.assertEqualExceptForNewlineEnd(expected, written)
  File "/private/tmp/nix-build-python3.8-pypandoc-1.5.drv-0/source/tests.py", line 409, in assertEqualExceptForNewlineEnd
    self.assertEqual(expected.rstrip('\n'), received.rstrip('\n'))
AssertionError: 'üäöîôû\n======' != '# üäöîôû'
- üäöîôû
?       -
+ # üäöîôû? ++
- ======
```

**Comment by doersino** [comment]
See #204 – recent versions of Pandoc emit ATX-style headings instead of underlining the heading texts with equals signs.

**Comment by sternenseemann** [comment]
#204 fixes it indeed as it is the patch we apply in nixpkgs nowadays.

**Comment by jayvdb** [comment]
This appears to have been fixed already.

**Comment by NicklasTegner** [comment]
This has indeed been fixed in our test cases, so I'll mark this issue as closed.
If you still encounter this issue, feel free to reopen.
