### ISSUE TITLE
Some pandoc options not working with extra_args

### ISSUE THREAD

**Issue by jmorim** [NicklasTegner/pypandoc#206]
E.g. `--template template.latex` and `--variable urlcolor=cyan`

mwe
```
import pypandoc

output = pypandoc.convert_file(
        'test.md',
        to = 'pdf',
        outputfile = 'test.pdf',
        extra_args = ['--template template.latex']
        )
```
returns 
```
Traceback (most recent call last):
  File "mwe.py", line 3, in <module>
    output = pypandoc.convert_file(
  File "C:\Python38\lib\site-packages\pypandoc\__init__.py", line 137, in convert_file
    return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
  File "C:\Python38\lib\site-packages\pypandoc\__init__.py", line 320, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "6" during conversion: b'Unknown option --template template.latex.\r\nTry pandoc --help for more information.\r\n'
shell returned 1
```

**Comment by doersino** [comment]
I believe you need to split the extra arguments into a list of strings, i.e. `['--template', 'template.latex']`.

As the readme notes (in a different context, but it also applies for your use case):

> This gotcha has to do with the way [`subprocess.Popen`](https://docs.python.org/2/library/subprocess.html#subprocess.Popen) works.

**Comment by NicklasTegner** [comment]
As the original author hasn't responded, I see this issue as resolved.
If not, feel free to open a new issue!
